### ISSUE TITLE
[Bug] OAuth app expiry times are updated wrongly

### ISSUE THREAD

**Issue by athiththan11** [wso2-extensions/identity-migration-resources#62]
### Description
The migration-client retrieves different configured expiry times related to OAuth apps from the Config Registry and trying to update the apps with the wrong values when migrating from Identity Component v5.3 to v5.4.

Both UserAccessTokenExpiryTime and RefreshTokenExpiryTime are getting updated with the ApplicationAccessTokenExpiryTime.

### Affected Migration Step
- Identity Component Migration from v5.3 to v5.4

**Comment by JKAUSHALYA** [comment]
Fixed in 819a361f1a2562579b6c09826374e52408a1929b
